[general]
import = ["~/.config/alacritty/themes/tango.toml"]

[font]
size = 12

[font.normal]
family = "Martian Mono"

[window]
opacity = 0.85

[keyboard]
bindings = [
    { key = "Backspace", mods = "Control | Alt", action = "ResetFontSize" },
]
